name: Deploy Documentation

on:
    workflow_dispatch: # Only run when manually triggered

jobs:
    deploy-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm ci

            - name: Generate documentation
              run: npm run generate-docs
              env:
                  NODE_ENV: development
                  PORT: 3001
                  CORS_ALLOWED_ORIGINS: http://localhost:3001
                  FIREBASE_PROJECT_ID: placeholder
                  FIREBASE_CLIENT_EMAIL: placeholder@placeholder.iam.gserviceaccount.com
                  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIplaceholder\n-----END PRIVATE KEY-----\n"

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
                  publish_branch: gh-pages
